language: node_js
os:
- linux
node_js:
- lts/*
script:
- npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: "public/"
  on:
    branch: master
env:
  global:
    secure: Bbsmz4wFtd0XxlPuY6dDMqWiKM/vvotB47VqSRGkv7Tf6k3yxdFobY0yCSCo437zxBUrcEBxPSI1w9ym9aLAfFOPnqfcx5+eRgkwdW89OD6QEtdaFmrxGNMH2lmb8qNC0Ep7E3oGvDgKkSWabc9aAbvnqDK0j93g9Re1nq8/LNKAq94wubvMJGjDDmS3GhqNbKydr18qqVKX719troOXCYT/5K2Xd+OxukFBms2YJ3o0yELWqatE8XDIWJnCucAvb0UDcCWnwEiX9SAXd3qST/zY2q8d27XiZV7LdmUmntCd/KHY5dxsHbM9ZIF4Tcqq5h3fAftFGDAFBz8IKYEUIS2Q7/PRSvX+SKcKPcNLc3uE9tL50zWcC8F6IsAjQD0yh+3FG/0dyRJWmh/zlqqjxVq5U7PuvK5n5rumwHyo9N9Zr5HZJ10bWJz7y4eCUvNa85u9T6eakJJsUsPtLJZbDvoavL6rVNoflt7XiklJ0qmCjXvbVcW7hgkQaYFETey+le1VDHmzJmuhXVk2C8DBi9eeiNldj6Pv1VMOVwYW8yKcj4U7V+6jbRBEQbkDBtVPVcXm00x3aG3rmrHh7GlilC4agh44C7O8pOX+pVW5pX1aa3iEbqGbegnCYTyXWorcQgmB5lLDOpu/zHdHjYvm3a5XjR0Wd+Q+IOwVFWlIs+k=
